### ISSUE TITLE
Error if a variable "contains" the formula expression

### ISSUE THREAD

**Issue by abigmo** [cole-brokamp/RFinfer#4]
In R 3.4.1 (Linux Ubuntu 16.04 64 bit) it happens that

>library(randomForest)
>data(airquality)
>d <- na.omit(airquality)
>form <- as.formula("Ozone ~ Solar.R + Wind + Temp + Month + Day")
>rf <- randomForest(form,data=d,keep.inbag=TRUE,sampsize=30,replace=FALSE,ntree=500)
>rfPredVar(rf,rf.data=d,CI=TRUE,tree.type='ci')
Error: object of type 'symbol' is not subsettable

while it works fine with

>library(randomForest)
>data(airquality)
>d <- na.omit(airquality)
>rf <- randomForest(Ozone ~ .,data=d,keep.inbag=TRUE,sampsize=30,replace=FALSE,ntree=500)
>rfPredVar(rf,rf.data=d,CI=TRUE,tree.type='ci')

Note that this happens only with tree.type="ci", maybe a problem in cforest, or in my code... I don't know...

Thanks for RFInfer,

 Alex

**Comment by cole-brokamp** [comment]
Thanks for the bug report Alex, this really helped a lot.  This was due to a strange way that `random.forest` objects store model formula.  If stored in an object rather then specified directly, an `eval()` is necessary. Should be fixed now in 4f52ac834749c64149b5ba61d10ca80d244cb22a.

**Comment by abigmo** [comment]
I am glad it helped a lot: you are too generous.
I was also looking also into the randomForestCI package by S. Wager.
Shouldn't the CI be extremely similar (i.e. almost identical) between the
two packages if in rfPredVar I use tree.type="rf"?

Thanks,
 Ales

2017-08-14 0:37 GMT+02:00 Cole Brokamp <notifications@github.com>:

**Comment by cole-brokamp** [comment]
Ideally, they would be.  This code was based on an older version of one of his manuscripts, which has since been deprecated in favor of a newer manuscript with an updated estimation strategy.  I haven't been monitoring this package too closely since these developments.  I would recommend using his package rather than RFinfer if the results differ.

**Comment by abigmo** [comment]
Ok, thanks for your intellectual honesty!
The variance from their package, is often resulting negative with my data,
even with large forest (>2000 trees)... I might ask them I guess.

Thanks!
Alex

2017-08-14 14:44 GMT+02:00 Cole Brokamp <notifications@github.com>:
